"""``vtkmodules.vtkCommonDataModel`` の最小スタブ。"""

from typing import Any

from vtkmodules.vtkCommonCore import vtkPoints

class vtkDataSetAttributes:
    def AddArray(self, array: Any) -> None: ...

class vtkUnstructuredGrid:
    @staticmethod
    def GetData(info: Any) -> vtkUnstructuredGrid: ...
    def ShallowCopy(self, src: Any) -> None: ...
    def GetPoints(self) -> vtkPoints: ...
    def SetPoints(self, points: vtkPoints) -> None: ...
    def GetPointData(self) -> vtkDataSetAttributes: ...
