"""``vtkmodules.vtkCommonCore`` の最小スタブ。"""

from typing import Any

class vtkDataArray:
    def SetName(self, name: str) -> None: ...

class vtkPoints:
    def __init__(self) -> None: ...
    def SetData(self, data: Any) -> None: ...
    def GetData(self) -> Any: ...
